# 2CSSID-TP01. Prétraitement

- Binôme 01 : ....
- Binôme 02 : ....

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from typing import Tuple

## I. Réalisation des algorithmes

Cette partie sert à améliorer la compréhension des algorithmes de préparation de données vus en
cours en les implémentant à partir de zéro. Pour ce faire, on va utiliser la bibliothèque numpy qui
est utile dans les calcules surtout matricielles.

### I.1. Normalisation

Ici, on va réaliser les deux fonctions de nomalisation : standard et min-max.
On va prendre une matrice $X[N, M]$ de $N$ échantillons et $M$ colonnes.
La normalisation standard d'une colonne $j$ peut être décrite comme : 
$$standard(X_j) = \frac{X_j - \mu(X_j)}{\sigma(X_j)}$$
La nomalisation min-max d'une colonne $j$ peut être décrite comme : 
$$minmax(X_j) = \frac{X_j - min(X_j)}{max(X_j) - min(X_j)}$$


In [3]:
# TODO compléter la standardisation d'une matrice
# Entrée : la matrice des données (N échantillons X  M caractéristiques)
# Sortie : vecteur de M moyennes, vecteur de M écart-types, une matrice normalisée
def norm_std(X: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    
    M= X.mean(axis=0) #vecteur de M moyennes initialisation
    E= X.std(axis=0) #vecteur de M écart-types initialisation
    Standard = X.copy().astype(np.float64) #matrice normalisée de type float
    
    for j in range(0,X.shape[1]): #pour chaque 𝑋𝑗
        Standard[:, j] = (Standard[:, j]-M[j])/E[j]
    return M, E, Standard


#=====================================================================
# TEST UNITAIRE
#=====================================================================
# (array([4. , 3. , 0.5]),
#  array([1.87082869, 2.        , 0.5       ]),
#  array([[ 1.60356745,  1.        , -1.        ],
#         [-1.06904497, -1.        ,  1.        ],
#         [-0.53452248,  1.        , -1.        ],
#         [ 0.        , -1.        ,  1.        ]]))
#---------------------------------------------------------------------

X = np.array([
    [7, 5, 0],
    [2, 1, 1],
    [3, 5, 0],
    [4, 1, 1],
])

norm_std(X)

(array([4. , 3. , 0.5]),
 array([1.87082869, 2.        , 0.5       ]),
 array([[ 1.60356745,  1.        , -1.        ],
        [-1.06904497, -1.        ,  1.        ],
        [-0.53452248,  1.        , -1.        ],
        [ 0.        , -1.        ,  1.        ]]))

In [4]:
# TODO compléter la standardisation d'une matrice
# Entrée : la matrice des données (N échantillons X  M caractéristiques)
# Sortie : vecteur de M max, vecteur de M min, une matrice normalisée
def norm_minmax(X: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    #inisialisation
    Vmax = np.array([])
    Vmin = np.array([])
    minmax = X.copy().astype(np.float64) #matrice normalisée de type float
    
    Imax = np.argmax(X, axis=0) #indices 
    Imin = np.argmin(X, axis=0)
    
    for j in range(0,X.shape[1]):
        Vmax = np.append(Vmax,X[Imax[j],j]) #récupérer 𝑚𝑎𝑥(𝑋𝑗)
        Vmin = np.append(Vmin,X[Imin[j],j]) #récupérer 𝑚𝑖𝑛(𝑋𝑗)
        minmax[:, j] = ((minmax[:, j]-minmax[Imin[j],j])/(minmax[Imax[j],j]-minmax[Imin[j],j]))
        
    return Vmax, Vmin, minmax

#=====================================================================
# TEST UNITAIRE
#=====================================================================
# (array([7, 5, 1]),
#  array([2, 1, 0]),
#  array([[1. , 1. , 0. ],
#         [0. , 0. , 1. ],
#         [0.2, 1. , 0. ],
#         [0.4, 0. , 1. ]]))
#---------------------------------------------------------------------

X = np.array([
    [7, 5, 0],
    [2, 1, 1],
    [3, 5, 0],
    [4, 1, 1],
])

norm_minmax(X)

(array([7., 5., 1.]),
 array([2., 1., 0.]),
 array([[1. , 1. , 0. ],
        [0. , 0. , 1. ],
        [0.2, 1. , 0. ],
        [0.4, 0. , 1. ]]))

### I.2. Encodage One-Hot

Etant donné un vecteur $A[N]$ représentant une caractéristique nominale donnée, on veut encoder les valeurs en utilisant One-Hot. Pour faciliter la tâche, on vous donne l'algorithme détaillé : 
1. Trouver les valeurs uniques dans le vecteur $A$ ; on appele ça : un vocabulaire $V$
1. Créer une matrice $X[N, |V|] en recopiant le vecteur $V$ $N$ fois. Dans python, on peut recopier un vecteur en utilisant l'instruction : [V] * N
1. Comparer l'égalité entre chaque ligne de $A$ et chaque ligne (qui est un vecteur) de $X$.
1. Transformer les booléens vers des entiers

In [5]:
# TODO compléter l'encodage One-Hot
# Entrée : un vecteur d'une caractéristique (N échantillons)
# Sortie : vecteur du vocabulaire V, matrice N X |V|
def one_hot(A: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    V = np.unique(A)
    X = np.zeros((A.shape[0], V.shape[0]), dtype=bool)
    A = A.T
    for i in range(0, A.shape[0]):
        X[i,:] = (V == A[i])

    X = X.astype(int)
    return V, X

#=====================================================================
# TEST UNITAIRE
#=====================================================================
# (array(['COLD', 'HOT', 'MILD'], dtype='<U4'),
#  array([[0, 1, 0],
#         [0, 0, 1],
#         [1, 0, 0],
#         [0, 1, 0],
#         [0, 0, 1]]))
#---------------------------------------------------------------------

A = np.array(['HOT', 'MILD', 'COLD', 'HOT', 'MILD'])
one_hot(A)

(array(['COLD', 'HOT', 'MILD'], dtype='<U4'),
 array([[0, 1, 0],
        [0, 0, 1],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]))

### I.3. Binarisation

Etant donné un vecteur $A[N]$ représentant une caractéristique numérique donnée, on veut encoder les valeurs en 0 ou 1 selon un seuil $s$.
La binarization d'un élément $A_i$ est donnée par :
$$A_i' = \begin{cases}
1 & \text{si } A_i \ge s\\
0 & \text{sinon}\\
\end{cases}$$

In [6]:
# TODO compléter la binarisation
# Entrée : un vecteur d'une caractéristique (N échantillons), un nombre
# Sortie : un vecteur binarisé (N échantillons)
def bin(A: np.ndarray, seuil: float) -> np.ndarray:
    return (A >= seuil).astype(int)

#=====================================================================
# TEST UNITAIRE
#=====================================================================
# array([1, 0, 0, 0, 1, 1])
#---------------------------------------------------------------------

A = np.array([5, 2, 1, -1, 6, 4])

bin(A, 4)

array([1, 0, 0, 0, 1, 1])

## II. Application et analyse

Cette partie sert à appliquer les algorithmes, modifier les paramètres et analyser les résultats.

### II.1. Lecture des données

On va lire 4 fichiers : 
- un fichier CSV avec des colonnes séparées par des virgules
- un fichier CSV avec des colonnes séparées par des point-virgules
- un fichier Sqlite 
- un fichier XML

In [7]:
adult1 = pd.read_csv("data/adult1.csv", skipinitialspace=True)
adult1.head(10)

age         workclass  education         Marital-status  \
0  39.0         State-gov  Bachelors          Never-married   
1  50.0  Self-emp-not-inc  Bachelors     Married-civ-spouse   
2  38.0           Private    HS-grad               Divorced   
3  53.0           Private       11th                    NaN   
4  28.0           Private  Bachelors     Married-civ-spouse   
5  37.0           Private    Masters     Married-civ-spouse   
6  49.0           Private        9th  Married-spouse-absent   
7  52.0  Self-emp-not-inc    HS-grad     Married-civ-spouse   
8  31.0           Private    Masters          Never-married   
9  42.0           Private  Bachelors     Married-civ-spouse   

          occupation     sex  Hours-per-week  class  
0       Adm-clerical    Male              40  <=50K  
1    Exec-managerial    Male              13  <=50K  
2  Handlers-cleaners    Male              40  <=50K  
3  Handlers-cleaners    Male              40  <=50K  
4     Prof-specialty  Female              40  <=50K  
5    Exec-managerial  Female              40  <=50K  
6      Other-service  Female              16  <=50K  
7    Exec-managerial    Male              45   >50K  
8     Prof-specialty  Female              50   >50K  
9    Exec-managerial    Male              40   >50K

In [8]:
noms = ["class", "age", "sex", "workclass", "education", "hours-per-week", "marital-status"]
adult2 = pd.read_csv("data/adult2.csv", skipinitialspace=True, sep=";", header=None, names=noms)
adult2.head(10)

class age               sex             workclass           education  \
0     N  25                 F               Private        Some-college   
1     N  18                 F               Private             HS-grad   
2     Y  47                 F  Private, Prof-school                  60   
3     Y  50                 M           Federal-gov           Bachelors   
4     N  47                 M          Self-emp-inc             HS-grad   
5     Y  43                 M               Private        Some-college   
6     N  46                 M               Private             5th-6th   
7     N  35                 M               Private           Assoc-voc   
8     N  41                 M               Private             HS-grad   
9  N,30   M  Private, HS-grad                    40  Married-civ-spouse   

       hours-per-week      marital-status  
0                  40  Married-civ-spouse  
1                  30       Never-married  
2  Married-civ-spouse                 NaN  
3                  55            Divorced  
4                  60            Divorced  
5                  40  Married-civ-spouse  
6                  40  Married-civ-spouse  
7                  40  Married-civ-spouse  
8                  48  Married-civ-spouse  
9                 NaN                 NaN

In [9]:
import sqlite3
#établir la connexion avec la base de données
con = sqlite3.connect("data/adult3.db")
#récupérer le résultat d'une réquête SQL sur cette connexion
adult3 = pd.read_sql_query("SELECT * FROM income", con)

#remplacer les valeurs "?" par NaN de numpy
adult3 = adult3.replace('?', np.nan)

adult3.head(10)

num  age         workclass     education marital-status sex  hours-per-day  \
0    1   76           Private       Masters        married   M            8.0   
1    2   44           Private     Bachelors        married   M           12.0   
2    3   47  Self-emp-not-inc       Masters         single   F           10.0   
3    4   20           Private  Some-college         single   F            8.0   
4    5   29           Private       HS-grad         single   M            8.0   
5    6   32      Self-emp-inc       HS-grad        married   M            8.0   
6    7   17               NaN          10th         single   F            6.4   
7    8   30           Private          11th         single   M            8.0   
8    9   31         Local-gov       HS-grad         single   F            8.0   
9   10   42           Private       HS-grad        married   M            8.0   

  class  
0     Y  
1     Y  
2     N  
3     N  
4     N  
5     Y  
6     N  
7     N  
8     N  
9     N

In [10]:
!pip install lxml

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
from lxml import etree
#créer le parser et spécifier qu'il doit valider le DTD
parser = etree.XMLParser(dtd_validation=True)
#analyser le fichier XML en utilisant ce parser
arbre = etree.parse("data/adult4.xml", parser)

def valeur_noeud(noeud):
    return noeud.text if noeud is not None else np.nan

noms2 = ["id", "age", "workclass", "education", "marital-status", "sex", "hours-per-week", "class"]
adult4 = pd.DataFrame(columns=noms2)

for candidat in arbre.getroot():
    idi = candidat.get("id")
    age = valeur_noeud(candidat.find("age"))
    workclass = valeur_noeud(candidat.find("workclass"))
    education = valeur_noeud(candidat.find("education"))
    marital = valeur_noeud(candidat.find("marital-status"))
    sex = valeur_noeud(candidat.find("sex"))
    hours = valeur_noeud(candidat.find("hours-per-week"))
    klass = valeur_noeud(candidat.find("class"))

    adult4 = pd.concat(
        [adult4, 
         pd.Series([idi, age, workclass, education, marital, sex, hours, klass],index=noms2).to_frame().T
        ], axis=0, ignore_index=True)
adult4.head(10)

id age         workclass     education marital-status sex hours-per-week  \
0  52  47         Local-gov  Some-college       divorced   F             38   
1  53  34           Private       HS-grad         single   F             40   
2  54  33           Private     Bachelors         single   F             40   
3  55  21           Private       HS-grad         single   M             35   
4  56  52               NaN       HS-grad       divorced   M             45   
5  57  48           Private       HS-grad        married   M             46   
6  58  23           Private     Bachelors         single   M             40   
7  59  71  Self-emp-not-inc  Some-college       divorced   M              2   
8  60  29           Private       HS-grad       divorced   M             60   
9  61  42           Private     Bachelors       divorced   M             50   

  class  
0     N  
1     N  
2     N  
3     N  
4     Y  
5     N  
6     N  
7     N  
8     N  
9     N

**TODO: Analyse** 
- Que remarquez-vous concernant l'ordre, le nombre et les noms des caractéristiques dans les 4 datasets ?
- Que remarquez-vous à propos des valeurs dans les 4 tables ?

**Réponse**
- On trouve que les 4 datasets ont presque les mêmes catactéristiques mais les noms et l'ordre de ces catactéristiques différent d'une dataset à une autre, de plus la 1ére dataset adult1 contient une colonne "occupation" qui n'existe pas dans les autres 3 datasets, il y a aussi des colonnes dupliquées : la colonne id du adult3 et la colonne num du adult4 qui représentent une seule catactéristique mais avec des noms différents, et cette catactéristique ne se trouve pas dans les 2 premiers datasets
- à propos des valeurs : des caractéristiques avec des valeurs manquantes (NA) en certains lignes, la caractéristique "hours-per-day" du adult3 est représetée par "hours-per-week" dans les autres datasets i.e une échelle différente, des caractéristiques avec un intervalle des valeurs possibles différentes( conflits de valeurs, par exemple "marital-status" dans adult3 : single, married, divorced et dans adult2 : Married-civ-spouse, Never-married, Divorced )

### II.2. Intégration des données

Dans cette section, on va appliquer des opérations sur les différentes tables. Vous devez à chaque fois figurer ce qu'on a fait et pourquoi.

In [12]:
# Afficher les noms des colonnes de adult3
list(adult3.columns)

['num',
 'age',
 'workclass',
 'education',
 'marital-status',
 'sex',
 'hours-per-day',
 'class']

In [13]:
adult3.rename(columns={"num": "id", "hours-per-day": "hours-per-week"}, inplace=True)
adult1.rename(columns={"Hours-per-week": "hours-per-week", "Marital-status": "marital-status"}, inplace=True)

# Afficher les noms des colonnes de adult3
list(adult3.columns)

['id',
 'age',
 'workclass',
 'education',
 'marital-status',
 'sex',
 'hours-per-week',
 'class']

**TODO: Analyse** 
- Quelle opération a-t-on appliqué ?
- Pourquoi ? (Quel est l'intérêt ?)
- Est-ce qu'en appliquant cette opération, on aura certains problèmes ?

**Réponse**
- L'opération appliquée est le renommage de certains des colonnes des datasets adult3 et adult1
- Pour que les datasets être homogènes entre eux et pour faciliter l'intégration des données de ces datasets (fusion) et donc éviter la duplication et avoir une seule colonne correspond à chaque caractéristique (i.e par exemple ne pas garder les deux colonnes num et id, au lieu si on fusion on garde une seule colonne id)
- Oui, si le nom d'une colonne est faux, le nouveau nom ne sera pas appliqué

In [14]:
ordre = ["age", "workclass", "education", "marital-status", "sex", "hours-per-week", "class"]
adult1 = adult1.reindex(ordre + ["occupation"], axis=1)
#print adult1.head()
adult2 = adult2.reindex(ordre, axis=1)
adult3 = adult3.reindex(ordre + ["id"], axis=1)
adult4 = adult4.reindex(ordre + ["id"], axis=1)

# Afficher les noms des colonnes de adult3
list(adult3.columns)

['age',
 'workclass',
 'education',
 'marital-status',
 'sex',
 'hours-per-week',
 'class',
 'id']

**TODO: Analyse** 
- Quelle opération a-t-on appliqué ?
- Pourquoi ? (Quel est l'intérêt ?)

**Réponse**
- Opération: réordonnement des colonnes (réorganisation)
- Pour faciliter l'exploration des données et puisque on doit fusionner les 4 tables et donc il faut avoir la même structure

In [15]:
# Afficher les deux premières lignes de la table adult3
adult3.head(2)

age workclass  education marital-status sex  hours-per-week class  id
0   76   Private    Masters        married   M             8.0     Y   1
1   44   Private  Bachelors        married   M            12.0     Y   2

In [16]:
adult3["hours-per-week"] *= 5

# Afficher les deux premières lignes de la table adult3
adult3.head(2)

age workclass  education marital-status sex  hours-per-week class  id
0   76   Private    Masters        married   M            40.0     Y   1
1   44   Private  Bachelors        married   M            60.0     Y   2

**TODO: Analyse** 
- Quelle opération a-t-on appliqué ?
- Pourquoi ? (Quel est l'intérêt ?)

**Réponse**
- Opération: la transformation de l'échelle
- Pour ne pas avoir des informations erronés concernant "hours-per-week" par exemple la moyenne, des comparaisons, etc

In [17]:
adult34 = pd.concat([adult3, adult4], ignore_index=True)
adult34.head(10)

age         workclass     education marital-status sex hours-per-week class  \
0  76           Private       Masters        married   M           40.0     Y   
1  44           Private     Bachelors        married   M           60.0     Y   
2  47  Self-emp-not-inc       Masters         single   F           50.0     N   
3  20           Private  Some-college         single   F           40.0     N   
4  29           Private       HS-grad         single   M           40.0     N   
5  32      Self-emp-inc       HS-grad        married   M           40.0     Y   
6  17               NaN          10th         single   F           32.0     N   
7  30           Private          11th         single   M           40.0     N   
8  31         Local-gov       HS-grad         single   F           40.0     N   
9  42           Private       HS-grad        married   M           40.0     N   

   id  
0   1  
1   2  
2   3  
3   4  
4   5  
5   6  
6   7  
7   8  
8   9  
9  10

**TODO: Analyse** 
- Quelle opération a-t-on appliqué ?
- Pourquoi ? (Quel est l'intérêt ?)

**Réponse**
- Opération: fusion des tables des données
-  Pour regrouper les données et garder une seule dataset qui sera traitée prochainement pour la construction des modéles

In [18]:
# Transformer le champs "id" à un entier
adult34["id"] = pd.to_numeric(adult34["id"], downcast="integer")
# Ordonner la table en se basant sur les valeurs de "id"
adult34 = adult34.sort_values(by="id")

# L'opération que vous devez deviner (une opération de vérification)
red = adult34[adult34.duplicated("id", keep=False)]
red

age    workclass     education marital-status  sex hours-per-week class  \
44   70      Private  Some-college         single    M           40.0     N   
94   70      Private  Some-college         single    M              8     N   
45   31      Private       HS-grad         single    F           30.0     N   
95   31      Private       HS-grad         single  NaN              6     N   
46   22      Private  Some-college        married    M           24.0     N   
96   22      Private  Some-college        married    M            4.8     N   
47   36      Private       HS-grad        widowed    F           24.0     N   
97  NaN      Private       HS-grad        widowed    F            4.8     N   
48   64      Private          11th        married    M           40.0     N   
98   64      Private          11th        married    M              8     N   
49   43          NaN  Some-college       divorced    F           40.0     N   
99   43  Federal-gov  Some-college       divorced    F              8     N   

    id  
44  45  
94  45  
45  46  
95  46  
46  47  
96  47  
47  48  
97  48  
48  49  
98  49  
49  50  
99  50

**TODO: Analyse** 
- Quelle opération a-t-on appliqué ?
- Pourquoi ? (Quel est l'intérêt ?)

**Réponse**
- Opération: vérification des doublons par rapport à la colonne "id"
- Pour supprimer ces doublons si ils existent car on ne doit pas avoir des enregistrements avec le même id

In [19]:
# Il y a un problème avec cette forme
# en attendant qu'il soit réglé
#adult34 = adult34.groupby("id").ffill()

adult34.update(adult34.groupby(['id']).ffill())
adult34.update(adult34.groupby(['id']).bfill())

# L'opération de vérification précédente
red = adult34[adult34.duplicated("id", keep=False)]
red

age    workclass     education marital-status sex hours-per-week class  id
44  70      Private  Some-college         single   M           40.0     N  45
94  70      Private  Some-college         single   M              8     N  45
45  31      Private       HS-grad         single   F           30.0     N  46
95  31      Private       HS-grad         single   F              6     N  46
46  22      Private  Some-college        married   M           24.0     N  47
96  22      Private  Some-college        married   M            4.8     N  47
47  36      Private       HS-grad        widowed   F           24.0     N  48
97  36      Private       HS-grad        widowed   F            4.8     N  48
48  64      Private          11th        married   M           40.0     N  49
98  64      Private          11th        married   M              8     N  49
49  43  Federal-gov  Some-college       divorced   F           40.0     N  50
99  43  Federal-gov  Some-college       divorced   F              8     N  50

**TODO: Analyse** 
- Quelle opération a-t-on appliqué ?
- Pourquoi ? (Quel est l'intérêt ?)

**Réponse**
- Opération: regroupement des enregistrements selon la valeur du "id" puis le remplissage pour les valeurs absentes par une valeur précédente dans le même groupe du "id" 
- Pour garder tous les valeurs des champs d'un enregistrement dupliqué et de ne les pas perdre lors du supression des doublons

In [20]:
adult34.drop_duplicates("id", keep="last", inplace=True)

# On refait la même opération précédente
red = adult34[adult34.duplicated("id", keep=False)]
red

Empty DataFrame
Columns: [age, workclass, education, marital-status, sex, hours-per-week, class, id]
Index: []

**TODO: Analyse** 
- Quelle opération a-t-on appliqué ?
- Pourquoi ? (Quel est l'intérêt ?)

**Réponse**
- Opération: pour un groupe d'enregistrement qui ont le même "id" on garde le dernier seulement qui a des champs rempliés à partir des enregistrement dubliqués qui'ils le précédent
- Pour la supression des enregistrements dupliqués

In [21]:
list(adult1.columns)

['age',
 'workclass',
 'education',
 'marital-status',
 'sex',
 'hours-per-week',
 'class',
 'occupation']

In [22]:
adult1.drop(["occupation"], axis=1, inplace=True)
adult34.drop(["id"], axis=1, inplace=True)

list(adult1.columns)

['age',
 'workclass',
 'education',
 'marital-status',
 'sex',
 'hours-per-week',
 'class']

**TODO: Analyse** 
- Quelle opération a-t-on appliqué ?
- Pourquoi ? (Quel est l'intérêt ?)

**Réponse**
- Opération: suppression du la Caractéristique "occupation" du table adult1 et la Caractéristique "id" du table adult34
- Car se sont des Caractéristiques inutiles (de plus) qui ne figure pas dans tous les datasets

In [23]:
# les différentes valeurs du colonne adult1.marital-status
adult1["marital-status"].unique()

array(['Never-married', 'Married-civ-spouse', 'Divorced', nan,
       'Married-spouse-absent', 'Separated', 'Married-AF-spouse'],
      dtype=object)

In [24]:
dic = {
    "Never-married": "single",
    "Married-civ-spouse": "married",
    "Married-spouse-absent": "married",
    "Married-AF-spouse": "married",
    "Divorced": "divorced",
    "Separated": "divorced",
    "Widowed": "widowed"
}
adult1["marital-status"] = adult1["marital-status"].map(dic)
adult2["marital-status"] = adult2["marital-status"].map(dic)

# les différentes valeurs du colonne adult1.marital-status après mappage
adult1["marital-status"].unique()

array(['single', 'married', 'divorced', nan], dtype=object)

**TODO: Analyse** 
- Quelle opération a-t-on appliqué ?
- Pourquoi ? (Quel est l'intérêt ?)

**Réponse**
- Opération: transformation des valeurs du "marital-status" chez adult1 et adult2
- Pour avoir une même représentation du caractéristique "marital-status" et un intervalle unifié avec des valeurs restreintes 

In [25]:
# On va appliquer la même opération sur d'autres caractéristiques
adult1["sex"] = adult1["sex"].map({"Female": "F", "Male": "M"})
adult1["class"] = adult1["class"].map({"<=50K": "N", ">50K": "Y"})

# Ensuite, on fusionne les tables dans une seule
adult = pd.concat([adult1, adult2, adult34], ignore_index=True)

# dimension de la table adult
adult.shape

(194, 7)

### II.3. Nétoyage des données

Ici, on va appliquer des opérations de nétoyage. C'est à vous de déviner quelle opération a-t-on utilisé et pourqoi.


In [26]:
# Afficher le nombre des valeurs nulles dans chaque colonne
adult.isnull().sum()

age                5
workclass         10
education          1
marital-status     4
sex                2
hours-per-week     2
class              0
dtype: int64

In [27]:
adult.dropna(subset=["workclass", "education", "marital-status", "sex", "hours-per-week", "class"], inplace=True)
adult.isnull().sum()

age               3
workclass         0
education         0
marital-status    0
sex               0
hours-per-week    0
class             0
dtype: int64

**TODO: Analyse** 
- Quelle opération a-t-on appliqué ?
- Pourquoi ? (Quel est l'intérêt ?)

**Réponse**
- Opération: supression des valeurs manquantes i.e les enregistrements avec une valeur "nan" pour chaque colonne sauf "age"
- Il est difficile de deviner les valeurs manquantes à cause de la nature des caractéristiques étudiées et le nombre de ces valeurs dans la dataset est petite et donc on les supprime pour nettoyer les enregistrements

In [28]:
adult["age"] = pd.to_numeric(adult["age"])
adult["age"] = adult.groupby(["class", "education"])["age"].transform(lambda x: x.fillna(int(round(x.mean()))))
adult.isnull().sum()

age               0
workclass         0
education         0
marital-status    0
sex               0
hours-per-week    0
class             0
dtype: int64

**TODO: Analyse** 
- Quelle opération a-t-on appliqué ?
- Pourquoi ? (Quel est l'intérêt ?)

**Réponse**
- Opération: remplissage des valeurs manquantes du "age" par la moyenne après le regroupement des enregistrements par "class" et "education"
- On peut garder les enregistrements qui ont pas une valeur du "age" car on a des outils qui peuvent aider à rapprocher la caractéristique "age" en remplaçant par la moyenne

### II.4. Transformation des données

In [29]:
adult["education"].head(6)

0    Bachelors
1    Bachelors
2      HS-grad
4    Bachelors
5      Masters
6          9th
Name: education, dtype: object

In [30]:
from sklearn.preprocessing import OrdinalEncoder
ord_enc = OrdinalEncoder()
# le résultat c'est un numpy.ndarray
education_enc = ord_enc.fit_transform(adult[["education"]])
education_enc[:6,]

array([[6.],
       [6.],
       [8.],
       [6.],
       [9.],
       [3.]])

**TODO: Analyse** 
- Quel est le type d'encodage utilisé ?
- A votre avis, dans quel cas peut-on utiliser ce type d'encodage ?

**Réponse**
- Type d'encodage : ordinal encoder, affectation des entiers à chaque valeur du caractéristique "education"
- On l'utilise dans le cas ou on travaille avec des données liées au classement de quelque chose avec des catégories non numériques

In [31]:
adult["sex"].head(6)

0    M
1    M
2    M
4    F
5    F
6    F
Name: sex, dtype: object

In [32]:
from sklearn.preprocessing import OneHotEncoder
onehot_enc = OneHotEncoder()
# le résultat c'est un numpy.ndarray
sex_enc = onehot_enc.fit_transform(adult[["sex"]])
sex_enc.toarray()[:6,]

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

**TODO: Analyse** 
- Quel est le type d'encodage utilisé ?
- A votre avis, dans quel cas peut-on utiliser ce type d'encodage ?

**Réponse**
- Type d'encodage : One-Hot
- Lorsque on a des données catégorielles à convertir qui ne sont pas ordinales, et avec les algorithmes d'apprentissage qui nécessitent des valeurs numériques et pas des catégories

In [33]:
adult["hours-per-week"] = pd.to_numeric(adult["hours-per-week"])
adult["hours-per-week"].head(3)

0    40.0
1    13.0
2    40.0
Name: hours-per-week, dtype: float64

In [34]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
# le résultat c'est un numpy.ndarray
hours_per_week_prop = min_max_scaler.fit_transform(adult[["hours-per-week"]])
hours_per_week_prop[:3,]

array([[0.49367089],
       [0.15189873],
       [0.49367089]])

In [35]:
# pour ajouter la nouvelle caractéristique au dataframe
adult["hours-per-week-prop"] = hours_per_week_prop
adult.head(3)

age         workclass  education marital-status sex  hours-per-week class  \
0  39.0         State-gov  Bachelors         single   M            40.0     N   
1  50.0  Self-emp-not-inc  Bachelors        married   M            13.0     N   
2  38.0           Private    HS-grad       divorced   M            40.0     N   

   hours-per-week-prop  
0             0.493671  
1             0.151899  
2             0.493671

**TODO: Analyse** 
- Comment la normalisation MinMax est calculée ?
- Décrire les valeurs résultats (plage de valeurs, etc.) ?
- Est-ce que les valeurs du dataset de test sont garanties d'être dans la plage ?
- Si oui, expliquer pouruoi. Si non, comment garantir la plage des valeurs ?

**Réponse**
- Normalisation MinMax(X) = (X - min(X))/(max(X) - min(X))
- Réduction de l’échelle des valeurs, les valeurs résultats sont entre 0 et 1 
- Non, ce n'est pas garanti. Une valeur peut dépasser 1
- Cette normalisation préserve les relations (distance proportionnelle) entre les valeurs de données d’origine, car chaque valeur est traité du même maniére : soustraction et division par des constantes

In [36]:
adult["age"].head(3)

0    39.0
1    50.0
2    38.0
Name: age, dtype: float64

In [37]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
# le résultat c'est un numpy.ndarray
age_normal = std_scaler.fit_transform(adult[["age"]])
age_normal[:3,]

array([[0.111269  ],
       [0.99962632],
       [0.03050924]])

**TODO: Analyse** 
- Comment la normalisation standard est calculée ?
- Décrire les valeurs résultats (plage de valeurs, etc.) ?

**Réponse**
- La normalisation standard consiste à soustraire la moyenne et à la diviser par l’écart type
- La variable/caractéristique standarisée devient centré réduite (la moyenne = 0 et l'écart type = 1), les valeurs résultats sont tout entre 0 et 1 et leur moyenne égale à zéro

In [38]:
adult["age"].head(10)

0     39.0
1     50.0
2     38.0
4     28.0
5     37.0
6     49.0
7     52.0
8     31.0
9     42.0
10    43.0
Name: age, dtype: float64

In [39]:
from sklearn.preprocessing import Binarizer

binarizer = Binarizer(threshold=40)
# le résultat c'est un numpy.ndarray
age_bin = binarizer.fit_transform(adult[["age"]])
age_bin[:10,]

array([[0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.]])

**TODO: Analyse** 
- Quelle est l'opération appliquée ici ?
- Quel est son rôle ?

**Réponse**
- Opération : Binarisation
- Rôle : convertir les valeurs numériques en valeurs booléennes en utilisant une valeur de seuil (ici égale à 40) toutes les valeurs supérieures au seuil seraient converties en 1 et toutes les valeurs inférieures au seuil seraient converties en 0, et donc elle élimine la moyenne de sorte que chaque valeur soit centrée sur zéro